name: BusinnerCI
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run an one-line script
        run: echo Hello, world!
        
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: dev.businner.com.br
    needs: build
    steps:
      - name: Script to deploy dev environment
        run: echo dev deployed
        
  deploy-hlg:
    runs-on: ubuntu-latest
    environment:
      name: hlg
      url: hlg.businner.com.br
    needs: deploy-dev
    steps:
      - name: Script to deploy hlg environment
        run: echo hlg deployed
      
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: businner.com.br
    needs: deploy-hlg
    steps:
      - name: Script to deploy to prod
        run: echo prod deployed
